import React from "react";

const LABELS: Record<string, string> = {
  active: "نشط",
  inactive: "غير نشط",
  paused: "متوقف",
  planning: "تخطيط",
  "in-progress": "قيد التنفيذ",
  review: "مراجعة",
  delivered: "تم التسليم",
  invoiced: "تمت الفوترة",
  closed: "مغلق",
  pending: "قيد الانتظار",
  completed: "مكتمل",
  "on-hold": "معلّق",
  assigned: "مسند",
  paid: "مدفوع",
  draft: "مسودة",
  sent: "مرسلة",
  overdue: "متأخرة",
  high: "عالية",
  medium: "متوسطة",
  low: "منخفضة",
  owner: "مالك",
  admin: "أدمن",
  team_member: "عضو فريق",
  service: "تقديم خدمة",
  supply: "توريد",
  third_party: "طرف ثالث",
  expired: "منتهي",
  terminated: "مفسوخ",
  cancelled: "ملغية",
  service_provider: "مقدم خدمة",
  strategic_partner: "شراكة استراتيجية",
  in_use: "قيد الاستخدام",
  available: "متاح",
  maintenance: "صيانة",
  equipment: "معدات",
  software: "برمجيات",
  license: "رخصة",
  account: "حساب",
  furniture: "أثاث",
  accepted: "مقبول",
  rejected: "مرفوض",
  lead: "عميل محتمل",
  contacted: "تم التواصل",
  proposal: "عرض مقدم",
  negotiation: "تفاوض",
  won: "فوز",
  lost: "خسارة",
  commercial_registration: "سجل تجاري",
  tax_certificate: "شهادة ضريبة",
  zakat_certificate: "شهادة زكاة",
  chamber_membership: "عضوية الغرفة",
  national_address: "العنوان الوطني",
  trademark: "علامة تجارية",
  other: "أخرى",
  valid: "ساري",
  expiring_soon: "قارب الانتهاء",
  requested: "مطلوب",
  ordered: "تم الطلب",
  received: "تم الاستلام",
  pending_approval: "بانتظار الموافقة",
  approved: "معتمد",
  full_time: "دوام كامل",
  part_time: "دوام جزئي",
  hourly: "دوام بالساعة",
  remote: "دوام عن بعد",
};

const COLORS: Record<string, string> = {
  active: "bg-emerald-100 text-emerald-700",
  paid: "bg-emerald-100 text-emerald-700",
  completed: "bg-emerald-100 text-emerald-700",
  delivered: "bg-emerald-100 text-emerald-700",
  "in-progress": "bg-blue-100 text-blue-700",
  assigned: "bg-blue-100 text-blue-700",
  sent: "bg-blue-100 text-blue-700",
  invoiced: "bg-blue-100 text-blue-700",
  pending: "bg-amber-100 text-amber-700",
  planning: "bg-amber-100 text-amber-700",
  draft: "bg-gray-200 text-gray-700",
  review: "bg-amber-100 text-amber-700",
  overdue: "bg-red-100 text-red-700",
  inactive: "bg-gray-200 text-gray-600",
  paused: "bg-gray-200 text-gray-600",
  closed: "bg-gray-200 text-gray-600",
  "on-hold": "bg-gray-200 text-gray-600",
  high: "bg-red-100 text-red-700",
  medium: "bg-amber-100 text-amber-700",
  low: "bg-gray-200 text-gray-600",
  owner: "bg-purple-100 text-purple-700",
  admin: "bg-indigo-100 text-indigo-700",
  team_member: "bg-gray-200 text-gray-600",
  service: "bg-blue-100 text-blue-700",
  supply: "bg-teal-100 text-teal-700",
  third_party: "bg-purple-100 text-purple-700",
  expired: "bg-gray-200 text-gray-600",
  terminated: "bg-red-100 text-red-700",
  cancelled: "bg-gray-200 text-gray-600",
  service_provider: "bg-sky-100 text-sky-700",
  strategic_partner: "bg-violet-100 text-violet-700",
  in_use: "bg-blue-100 text-blue-700",
  available: "bg-emerald-100 text-emerald-700",
  maintenance: "bg-amber-100 text-amber-700",
  equipment: "bg-gray-200 text-gray-700",
  software: "bg-indigo-100 text-indigo-700",
  license: "bg-purple-100 text-purple-700",
  account: "bg-teal-100 text-teal-700",
  furniture: "bg-gray-200 text-gray-700",
  accepted: "bg-emerald-100 text-emerald-700",
  rejected: "bg-red-100 text-red-700",
  lead: "bg-gray-200 text-gray-600",
  contacted: "bg-sky-100 text-sky-700",
  proposal: "bg-amber-100 text-amber-700",
  negotiation: "bg-blue-100 text-blue-700",
  won: "bg-emerald-100 text-emerald-700",
  lost: "bg-red-100 text-red-700",
  commercial_registration: "bg-blue-100 text-blue-700",
  tax_certificate: "bg-teal-100 text-teal-700",
  zakat_certificate: "bg-indigo-100 text-indigo-700",
  chamber_membership: "bg-amber-100 text-amber-700",
  national_address: "bg-sky-100 text-sky-700",
  trademark: "bg-purple-100 text-purple-700",
  other: "bg-gray-200 text-gray-600",
  valid: "bg-emerald-100 text-emerald-700",
  expiring_soon: "bg-amber-100 text-amber-700",
  requested: "bg-gray-200 text-gray-600",
  ordered: "bg-blue-100 text-blue-700",
  received: "bg-teal-100 text-teal-700",
  pending_approval: "bg-orange-100 text-orange-700",
  approved: "bg-emerald-100 text-emerald-700",
  full_time: "bg-blue-100 text-blue-700",
  part_time: "bg-teal-100 text-teal-700",
  hourly: "bg-amber-100 text-amber-700",
  remote: "bg-violet-100 text-violet-700",
};

export const StatusBadge: React.FC<{ status: string; className?: string }> = ({
  status,
  className = "",
}) => (
  <span
    className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold whitespace-nowrap ${
      COLORS[status] ?? "bg-gray-100 text-gray-700"
    } ${className}`}
  >
    {LABELS[status] ?? status}
  </span>
);
